# Generated by Django 4.2 on 2023-06-02 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='public_date',
            field=models.DateField(default=datetime.date(2023, 6, 2)),
        ),
    ]
