# Generated by Django 4.2 on 2023-05-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
