# Generated by Django 4.2 on 2023-05-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comentarios_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comentarios',
            new_name='Comentario',
        ),
    ]
