# Generated by Django 4.2 on 2023-06-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='job',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='place',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AlterField(
            model_name='place',
            name='codigo_postal',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.AddField(
            model_name='empleado',
            name='job',
            field=models.ManyToManyField(to='Empleados.job'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='place',
            field=models.ManyToManyField(to='Empleados.place'),
        ),
        migrations.AddField(
            model_name='job',
            name='salario',
            field=models.ManyToManyField(to='Empleados.salary'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ManyToManyField(to='Empleados.country'),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.ManyToManyField(to='Empleados.location'),
        ),
    ]
