# Generated by Django 4.2 on 2023-06-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='andress',
            new_name='adress',
        ),
    ]
